using System;
using System.Collections.Generic;
using System.Text;

namespace Delnorte.Terravision.Abstractions.Models
{
    public class MeasurementTaxDescriptor
    {
        // PROPIETOR´S ID NUMBER
        // MUNICIPALITY ACCOUNT NUMBER
        // OWNERS PHONE NUMBER

        // SIDEWALK STATE
        // MEASUREMENT TO ADJACENT PROPERTY / STREET NORTH
        // MEASUREMENT TO ADJACENT PROPERTY / STREET SOUTH
        // MEASUREMENT TO ADJACENT PROPERTY / STREET EAST
        // MEASUREMENT TO ADJACENT PROPERTY / STREET WEST
        // NUMBER OF FLOOR LEVELS
        // PROPERTY VALUE ACCORDING TO CADASTRE
        // TYPE OF STREET WHERE PROPERTY IS LOCATED
        // STREET WIDE WHERE PROPERTY IS LOCATED NORTH
        // STREET WIDE WHERE PROPERTY IS LOCATED SOUTH
        // STREET WIDE WHERE PROPERTY IS LOCATED WEST
        // STREET WIDE WHERE PROPERTY IS LOCATED EAST
        // SERVICE PROVIDED BY THE MUNICIPALITY AT THE PROPERTY
    }
}
